### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by chldppwls12** [team-B-free/01-LabQ#2]
## 종류
ISSUE 종류를 선택하세요

- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

<br/>

## 내용
- 프로젝트 초기 세팅

<br/>

## 체크리스트
- [x] 프로젝트 구조 생성
- [x] 예시 작성

**Comment by StarFace90** [comment]
완료된 작업이므로 Close 합니다
